### PR TITLE
Don't inherit parent Minimum Level for inline sublogger configuration

### LINKED ISSUE #1346: Sublogger Ignoring Events from Parent Logger
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog.AspNetCore 2.1.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
I set a Default MinimumLevel in my Serilog configuration of Debug, and override the MinumumLevel of one of my SourceContexts to "Verbose".
If I log directly to a Sink (File Sink, for example), it works as expected, with everything except the overridden source being filtered to Debug or higher, but Verbose events making it through for the overridden source.
If I instead put a sub-logger between the main logger and the file sink (to add a filter or something), the Verbose events from the overridden source don't make it through.

Here is a snippet from my appsettings.json configuration file:

```
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "System": "Information",
        "Microsoft": "Information",
        "Namespace.BenchmarkTimer": "Verbose"
      }
    },
    "WriteTo": [
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "Filter": [
              {
                "Name": "ByIncludingOnly",
                "Args": {
                  "expression": "StartsWith(SourceContext, 'Namespace.BenchmarkTimer')"
                }
              }
            ],
            "WriteTo": [
              {
                "Name": "File",
                "Args": {
                  "path": "d:\\path-to-log-folder\\Benchmark Timer.txt"
                }
              }
            ]
          }
        }
      }
    ]
  },
```

**Please describe the expected behavior?**
All of the events from the parent logger make it through to the sinks configured in the sub-logger.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
Configure an application as described above. Write verbose logs from SourceContext "Namespace.BenchmarkTimer". The verbose events will not make it to the sub-logger's configured File Sink.

**Note**: I did try setting restrictedToMinimumLevel to "Verbose" on the sub-logger, which didn't make a difference.

### PR DESCRIPTION
**Pull request by skomis-mm**
**What issue does this PR address?**
Fixes #1346 , #1453 

**Does this PR introduce a breaking change?**
Behavior change for subloggers configured inline when no explicit default level specified for them.

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/serilog/serilog/blob/dev/CONTRIBUTING.md)
- [x] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**
Inheriting minimum level was done before overrides where introduced, so it doesn't take them into account now for subloggers which results in counterintuitive behavior.

### CODE REVIEW

File: src/Serilog/Configuration/LoggerSinkConfiguration.cs [hunk 1]
```diff
@@ -128,7 +128,11 @@ internal LoggerSinkConfiguration(LoggerConfiguration loggerConfiguration, Action
 
             var lc = new LoggerConfiguration();
 
+            // apply inherited configuration except minimum level
+            // since parent logger can have overrides
             _applyInheritedConfiguration(lc);
+            lc.MinimumLevel.Is(LevelAlias.Minimum);
```
Comment (nblumhardt) [inline src/Serilog/Configuration/LoggerSinkConfiguration.cs:134]: Since `_applyInheritedConfiguration` ends up calling:

```csharp
        void ApplyInheritedConfiguration(LoggerConfiguration child)
        {
            if (_levelSwitch != null)
                child.MinimumLevel.ControlledBy(_levelSwitch);
            else
                child.MinimumLevel.Is(_minimumLevel);
        }
```

it seems like removing that call here might be a cleaner fix?

I had a quick attempt at figuring out the original purpose of `_applyInheritedConfiguration` and can't track it down; I suspect it may have been part of an earlier version that took advantage of `Logger` directly implementing `ILogEventSink.Emit()` (without any level check), but can't immediately tell from the source.

Removing it entirely seems not to break any tests. Am I missing anything?

**Comment by nblumhardt** [comment]
Sorry I missed your mention/comments on 1453 - I've kept meaning to loop back around to this :sweat:

Making some time to catch up, now.

File: src/Serilog/Configuration/LoggerSinkConfiguration.cs (hunk 1 above)
Comment (skomis-mm) [reply src/Serilog/Configuration/LoggerSinkConfiguration.cs:134]: I've tracked it down to this [pr](https://github.com/serilog/serilog/pull/654). Part of it was the fix for [804](https://github.com/serilog/serilog/issues/804#issuecomment-231665651) issue.

The issue was about case with default minimum level of the root less than `Information` which results in explicit setting minimum for subloggers by users. 

The open question - why it was choosen the same as for the parent instead of `Verbose`..

Hint about `Logger` as `ILogEventSink` led me to such examples:

Behavior before this pr:
```csharp
new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.Sink(
        new LoggerConfiguration()
            .MinimumLevel.Fatal()
            .WriteTo.Console()
            .CreateLogger())
    .CreateLogger()
    .Verbose("oops"); // surpasse the Fatal filter
```
but
```csharp
new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.Sink(
        new LoggerConfiguration()
            .MinimumLevel.Fatal()
            .WriteTo.Logger(lc => lc.WriteTo.Console())
            .CreateLogger())
    .CreateLogger()
    .Verbose("oops"); // suppressed by the sublogger's Fatal filter
```

After this pr both examples will result in surpassing the Fatal filter. So it actually make the behavior consistent :)

So it makes sense to remove those lines as you pointed.

**Comment by skomis-mm** [comment]
Removed `ApplyInheritedConfiguration` since it was used just in one place

**Comment by nblumhardt** [comment]
LGTM :+1:
